site_name: Material de estudo
site_url: http://127.0.0.1:8000/
site_description: Site com a documentação dos estudos feitos por mim.
copyright: Samuel Mesquita da Fonseca
nav:
    - Home: index.md
    - Boas Praticas: 
      - S.O.L.I.D: solid.md
theme:
  name: material
  palette:
    primary: deep purple
  icon:
    admonition:
      info: octicons/info-16
plugins:
  - search:
      lang: pt
  - glightbox
markdown_extensions:
  - toc:
      title: Tópicos
  - tables
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
